import Image from "next/image";

/**
 * Cover shown on tasks with no uploaded feature image.
 *
 * Generated by `scripts/generate-default-cover.mjs` rather than sourced, so
 * the palette stays reviewable as code. A mid-tone was chosen because one
 * static file has to sit on both the light and dark content surfaces.
 */
export const DEFAULT_TASK_COVER = "/task-cover-default.png";

interface TaskCoverProps {
  /** The task's feature image. When absent, the default cover is used. */
  src?: string | null;
  /** Passed to `next/image`; defaults to the task-grid layout. */
  sizes?: string;
  /** Set on an above-the-fold cover so it is not lazy-loaded. */
  priority?: boolean;
  className?: string;
}

const GRID_SIZES = "(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 25vw";

export default function TaskCover({
  src,
  sizes = GRID_SIZES,
  priority = false,
  className = "",
}: TaskCoverProps) {
  return (
    <div className={`relative w-full overflow-hidden ${className}`}>
      <Image
        // `||` rather than `??`: the API stores a cleared cover as "" in some
        // paths and null in others, and both mean "no image".
        src={src || DEFAULT_TASK_COVER}
        alt=""
        fill
        sizes={sizes}
        priority={priority}
        className="object-cover transition-transform duration-500 group-hover:scale-[1.04]"
      />
    </div>
  );
}
